### ISSUE TITLE
Error with chroot package

### ISSUE THREAD

**Issue by DieterKoblenz** [Fornoth/spotify-connect-web#13]
I'm getting the following error when trying to run the chroot package.

SpInit: 0
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    connect_app = Connect(web_error_callback)
  File "/usr/src/app/connect.py", line 75, in **init**
    lib.SpPlaybackUpdateVolume(mixer_volume)
OverflowError: can't convert negative number to unsigned

**Comment by DieterKoblenz** [comment]
Finally used another card and got it up and running.
