### ISSUE TITLE
Manual build won't start

### ISSUE THREAD

**Issue by thoughtgap** [Fornoth/spotify-connect-web#132]
I've seen that a couple of new features like #83 were published after the last pre-packaged release and wanted to try them out.

I did
```
apt-get install python-dev libffi-dev libasound2-dev
pip install -r requirements.txt
```
and made `main.py` executable.

Launching it results in the following error:

```
pi@pi2:~/spotify-connect-web $ ./main.py --bitrate 320 --name raspi2 --playback_device hw:1 --lastfm_credentials lastfm_credentials.json
Traceback (most recent call last):
  File "./main.py", line 14, in <module>
    from connect_ffi import ffi, lib
  File "/home/pi/spotify-connect-web/connect_ffi.py", line 4, in <module>
    ffi = FFI()
  File "/home/pi/.local/lib/python2.7/site-packages/cffi/api.py", line 46, in __init__
    import _cffi_backend as backend
ImportError: libffi.so.5: cannot open shared object file: No such file or directory
```

I've tried to (re)install libffi6, it reports back just fine.

Could anyone help me? Thank you.

**Comment by Fornoth** [comment]
I've released a new version with those features
https://github.com/Fornoth/spotify-connect-web/releases/tag/0.0.4-alpha
