### ISSUE TITLE
Error wile starting the script

### ISSUE THREAD

**Issue by tompointexe** [Fornoth/spotify-connect-web#148]
> ./spotify-connect-web --username my.email@gmail.com --password myverylongpassword --bitrate 320 --name Raspi --playback_device spotify
Loading Spotify library...
Last.fm: incomplete credentials, not launched
Traceback (most recent call last):
  File "loader.py", line 3, in <module>
  File "runpy.py", line 180, in run_module
  File "runpy.py", line 72, in _run_code
  File "/home/osmc/Skripte/spotify-connect-web/main.py", line 15, in <module>
    from connect import Connect
  File "/home/osmc/Skripte/spotify-connect-web/connect.py", line 9, in <module>
    from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
  File "/home/osmc/Skripte/spotify-connect-web/console_callbacks.py", line 25, in <module>
    audio_arg_parser.add_argument('--mixer', '-m', help='alsa mixer name for volume control', default=alsa.mixers()[0])
alsaaudio.ALSAAudioError: Invalid argument [default]
Failed to execute script loader

Can someone help me , Thanks

**Comment by TomAvecLeVdsl** [comment]
> ./spotify-connect-web --username my.email@gmail.com --password myverylongpassword --bitrate 320 --name Raspi --playback_device spotify
Loading Spotify library...
Last.fm: incomplete credentials, not launched
Traceback (most recent call last):
  File "loader.py", line 3, in <module>
  File "runpy.py", line 180, in run_module
  File "runpy.py", line 72, in _run_code
  File "/home/osmc/Skripte/spotify-connect-web/main.py", line 15, in <module>
    from connect import Connect
  File "/home/osmc/Skripte/spotify-connect-web/connect.py", line 9, in <module>
    from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
  File "/home/osmc/Skripte/spotify-connect-web/console_callbacks.py", line 25, in <module>
    audio_arg_parser.add_argument('--mixer', '-m', help='alsa mixer name for volume control', default=alsa.mixers()[0])
alsaaudio.ALSAAudioError: Invalid argument [default]
Failed to execute script loader

Can someone help me , Thanks
