### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by isabido** [Fornoth/spotify-connect-web#29]
RPI2 Archlinux.  (in chroot instalation, runing OK)

This version:
https://github.com/sashahilton00/spotify-connect-resources/blob/master/armhf%20version/libspotify_embedded_shared.so

All requeriments.txt install.

This error to launch:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from connect_ffi import ffi, lib
  File "/root/spotify-connect-web-master/connect_ffi.py", line 4
    print "Loading Spotify library..."
                                     ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by isabido** [comment]
Pyhton3 had installed instead of python2
