### ISSUE TITLE
alsaaudio.ALSAAudioError: Invalid argument [default]

### ISSUE THREAD

**Issue by awiouy** [Fornoth/spotify-connect-web#67]
Hello,

I am trying to run spotify-connect-web (Pyinstaller Test Release 0.0.3) on LibreELEC (LibreELEC 7.0 on a RPi2 and LibreELEC 8.0 on a RPi3). Whatever parameters I pass to ./spotify-connect-web, I get the following error:

```
./spotify-connect-web
Loading Spotify library...
Traceback (most recent call last):
  File "loader.py", line 3, in <module>
  File "runpy.py", line 180, in run_module
  File "runpy.py", line 72, in _run_code
  File "/storage/downloads/sc/spotify-connect-web/main.py", line 14, in <module>
    from connect import Connect
  File "/storage/downloads/sc/spotify-connect-web/connect.py", line 9, in <module>
    from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
  File "/storage/downloads/sc/spotify-connect-web/console_callbacks.py", line 24, in <module>
    audio_arg_parser.add_argument('--mixer', '-m', help='alsa mixer name for volume control', default=alsa.mixers()[0])
alsaaudio.ALSAAudioError: Invalid argument [default]
Failed to execute script loader
```

The information below may be relevant to assess the issue:

```
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
```

Thank you in advance for helping me solving this issue, and regards,
@

**Comment by awiouy** [comment]
I have managed to run spotify-connect-web by creating the following /storage/.config/asound.conf:

```
pcm.!default {
        type hw
        card 0
}

ctl.!default {
        type hw
        card 0
}
```

spotify-connect-web does however not play music (no sound).

Thank you in advance for helping me solving this issue, and regards,
@

**Comment by awiouy** [comment]
I solved the issue by resorting to LibreELEC's own libasound.so.2 and passing -o hw:0,1 to spotify-connect-web. Thank you for this program.
@
